package internal

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	descriptor "ocm.software/open-component-model/bindings/go/descriptor/runtime"
	descriptorv2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	"ocm.software/open-component-model/bindings/go/oci/spec/repository/v1/oci"
	ociv1alpha1 "ocm.software/open-component-model/bindings/go/oci/spec/transformation/v1alpha1"
	"ocm.software/open-component-model/bindings/go/runtime"
	transformv1alpha1 "ocm.software/open-component-model/bindings/go/transform/spec/v1alpha1"
)

func localBlobTestRepo() *oci.Repository {
	return &oci.Repository{
		Type:    runtime.Type{Name: oci.Type, Version: "v1"},
		BaseUrl: "ghcr.io",
	}
}

func TestUploadAsLocalResource_OCI(t *testing.T) {
	transform, err := uploadAsLocalResource(localBlobTestRepo(), "comp", "1.0.0", "addRes1", "getRes1", "my/image:v1", "comp@1.0.0 [Add my-image]")
	require.NoError(t, err)
	assert.Equal(t, ociv1alpha1.OCIAddLocalResourceV1alpha1, transform.Type)
	assert.Equal(t, "addRes1", transform.ID)
	assert.Equal(t, "comp@1.0.0 [Add my-image]", transform.Label)
	require.NotNil(t, transform.Spec)

	// A non-empty referenceName is written to the local blob access (OCI legacy compat).
	access := transform.Spec.Data["resource"].(map[string]any)["access"].(map[string]any)
	assert.Equal(t, "my/image:v1", access["referenceName"])
}

// referenceName is an OCI-only legacy field. When no reference name is supplied (every
// non-OCI content type: git, github, s3, wget), the generated local blob access must omit
// the field entirely rather than carrying an empty one.
func TestUploadAsLocalResource_OmitsEmptyReferenceName(t *testing.T) {
	transform, err := uploadAsLocalResource(localBlobTestRepo(), "comp", "1.0.0", "addRes1", "getRes1", "", "comp@1.0.0 [Add blob]")
	require.NoError(t, err)

	access := transform.Spec.Data["resource"].(map[string]any)["access"].(map[string]any)
	_, hasReferenceName := access["referenceName"]
	assert.False(t, hasReferenceName)
}

// A localBlob source already carrying a referenceName (e.g. one set by an earlier OCI
// by-value transfer) is re-transferred through processLocalBlob, which passes the whole
// source resource through verbatim. The referenceName must survive: it is neither dropped
// nor rebuilt, so an existing descriptor keeps its field.
func TestProcessLocalBlob_PreservesExistingReferenceName(t *testing.T) {
	var rawAccess runtime.Raw
	require.NoError(t, runtime.NewScheme(runtime.WithAllowUnknown()).Convert(&descriptorv2.LocalBlob{
		Type:           runtime.NewVersionedType(descriptorv2.LocalBlobAccessType, descriptorv2.LocalBlobAccessTypeVersion),
		LocalReference: "sha256:abc",
		ReferenceName:  "org/image:v1",
	}, &rawAccess))

	resource := descriptorv2.Resource{
		ElementMeta: descriptorv2.ElementMeta{
			ObjectMeta: descriptorv2.ObjectMeta{Name: "blob", Version: "1.0.0"},
		},
		Type:     "blob",
		Relation: descriptorv2.ExternalRelation,
		Access:   &rawAccess,
	}

	val := &discoveryValue{
		Descriptor: &descriptor.Descriptor{
			Component: descriptor.Component{
				ComponentMeta: descriptor.ComponentMeta{
					ObjectMeta: descriptor.ObjectMeta{Name: "ocm.software/comp", Version: "1.0.0"},
				},
			},
		},
		SourceRepository: localBlobTestRepo(),
	}

	tgd := &transformv1alpha1.TransformationGraphDefinition{}
	ids := map[int]string{}
	// Empty ociImageReference selects the by-value local-blob embedding path.
	require.NoError(t, processLocalBlob(resource, "comp1", val, tgd, localBlobTestRepo(), ids, 0, ""))

	require.Len(t, tgd.Transformations, 2)
	add := tgd.Transformations[1]
	getID := tgd.Transformations[0].ID
	// The resource is forwarded verbatim from the Get step, so any referenceName it carries
	// is preserved rather than regenerated by uploadAsLocalResource.
	assert.Equal(t, "${"+getID+".output.resource}", add.Spec.Data["resource"])
}
