//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package internal

import (
	v1alpha1 "ocm.software/open-component-model/bindings/go/blob/filesystem/spec/access/v1alpha1"
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileCleanupOutput) DeepCopyInto(out *FileCleanupOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileCleanupOutput.
func (in *FileCleanupOutput) DeepCopy() *FileCleanupOutput {
	if in == nil {
		return nil
	}
	out := new(FileCleanupOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileCleanupSpec) DeepCopyInto(out *FileCleanupSpec) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]*v1alpha1.File, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.File)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileCleanupSpec.
func (in *FileCleanupSpec) DeepCopy() *FileCleanupSpec {
	if in == nil {
		return nil
	}
	out := new(FileCleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileCleanupTransformation) DeepCopyInto(out *FileCleanupTransformation) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(FileCleanupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(FileCleanupOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileCleanupTransformation.
func (in *FileCleanupTransformation) DeepCopy() *FileCleanupTransformation {
	if in == nil {
		return nil
	}
	out := new(FileCleanupTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *FileCleanupTransformation) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JFrogHelmUploadComponentVersion) DeepCopyInto(out *JFrogHelmUploadComponentVersion) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JFrogHelmUploadComponentVersion.
func (in *JFrogHelmUploadComponentVersion) DeepCopy() *JFrogHelmUploadComponentVersion {
	if in == nil {
		return nil
	}
	out := new(JFrogHelmUploadComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JFrogHelmUploadOutput) DeepCopyInto(out *JFrogHelmUploadOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JFrogHelmUploadOutput.
func (in *JFrogHelmUploadOutput) DeepCopy() *JFrogHelmUploadOutput {
	if in == nil {
		return nil
	}
	out := new(JFrogHelmUploadOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JFrogHelmUploadSpec) DeepCopyInto(out *JFrogHelmUploadSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.ComponentVersion != nil {
		in, out := &in.ComponentVersion, &out.ComponentVersion
		*out = new(JFrogHelmUploadComponentVersion)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JFrogHelmUploadSpec.
func (in *JFrogHelmUploadSpec) DeepCopy() *JFrogHelmUploadSpec {
	if in == nil {
		return nil
	}
	out := new(JFrogHelmUploadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JFrogHelmUploadTransformation) DeepCopyInto(out *JFrogHelmUploadTransformation) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(JFrogHelmUploadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(JFrogHelmUploadOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JFrogHelmUploadTransformation.
func (in *JFrogHelmUploadTransformation) DeepCopy() *JFrogHelmUploadTransformation {
	if in == nil {
		return nil
	}
	out := new(JFrogHelmUploadTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *JFrogHelmUploadTransformation) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
