//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package internal

import (
	_ "embed"
)

//go:embed schemas/FileCleanupOutput.schema.json
var schemaFileCleanupOutput []byte

//go:embed schemas/FileCleanupSpec.schema.json
var schemaFileCleanupSpec []byte

//go:embed schemas/FileCleanupTransformation.schema.json
var schemaFileCleanupTransformation []byte

//go:embed schemas/JFrogHelmUploadComponentVersion.schema.json
var schemaJFrogHelmUploadComponentVersion []byte

//go:embed schemas/JFrogHelmUploadOutput.schema.json
var schemaJFrogHelmUploadOutput []byte

//go:embed schemas/JFrogHelmUploadSpec.schema.json
var schemaJFrogHelmUploadSpec []byte

//go:embed schemas/JFrogHelmUploadTransformation.schema.json
var schemaJFrogHelmUploadTransformation []byte

// JSONSchema returns the JSON Schema for FileCleanupOutput.
func (FileCleanupOutput) JSONSchema() []byte {
	return schemaFileCleanupOutput
}

// JSONSchema returns the JSON Schema for FileCleanupSpec.
func (FileCleanupSpec) JSONSchema() []byte {
	return schemaFileCleanupSpec
}

// JSONSchema returns the JSON Schema for FileCleanupTransformation.
func (FileCleanupTransformation) JSONSchema() []byte {
	return schemaFileCleanupTransformation
}

// JSONSchema returns the JSON Schema for JFrogHelmUploadComponentVersion.
func (JFrogHelmUploadComponentVersion) JSONSchema() []byte {
	return schemaJFrogHelmUploadComponentVersion
}

// JSONSchema returns the JSON Schema for JFrogHelmUploadOutput.
func (JFrogHelmUploadOutput) JSONSchema() []byte {
	return schemaJFrogHelmUploadOutput
}

// JSONSchema returns the JSON Schema for JFrogHelmUploadSpec.
func (JFrogHelmUploadSpec) JSONSchema() []byte {
	return schemaJFrogHelmUploadSpec
}

// JSONSchema returns the JSON Schema for JFrogHelmUploadTransformation.
func (JFrogHelmUploadTransformation) JSONSchema() []byte {
	return schemaJFrogHelmUploadTransformation
}
