//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Helm.schema.json
var schemaHelm []byte

// JSONSchema returns the JSON Schema for Helm.
func (Helm) JSONSchema() []byte {
	return schemaHelm
}
