//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GetWget.schema.json
var schemaGetWget []byte

//go:embed schemas/GetWgetOutput.schema.json
var schemaGetWgetOutput []byte

//go:embed schemas/GetWgetSpec.schema.json
var schemaGetWgetSpec []byte

// JSONSchema returns the JSON Schema for GetWget.
func (GetWget) JSONSchema() []byte {
	return schemaGetWget
}

// JSONSchema returns the JSON Schema for GetWgetOutput.
func (GetWgetOutput) JSONSchema() []byte {
	return schemaGetWgetOutput
}

// JSONSchema returns the JSON Schema for GetWgetSpec.
func (GetWgetSpec) JSONSchema() []byte {
	return schemaGetWgetSpec
}
