//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package localblob

import (
	_ "embed"
)

//go:embed schemas/MoveLocalBlobs.schema.json
var schemaMoveLocalBlobs []byte

//go:embed schemas/MoveLocalBlobsOutput.schema.json
var schemaMoveLocalBlobsOutput []byte

//go:embed schemas/MoveLocalBlobsSpec.schema.json
var schemaMoveLocalBlobsSpec []byte

// JSONSchema returns the JSON Schema for MoveLocalBlobs.
func (MoveLocalBlobs) JSONSchema() []byte {
	return schemaMoveLocalBlobs
}

// JSONSchema returns the JSON Schema for MoveLocalBlobsOutput.
func (MoveLocalBlobsOutput) JSONSchema() []byte {
	return schemaMoveLocalBlobsOutput
}

// JSONSchema returns the JSON Schema for MoveLocalBlobsSpec.
func (MoveLocalBlobsSpec) JSONSchema() []byte {
	return schemaMoveLocalBlobsSpec
}
