//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package localblob

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveLocalBlobs) DeepCopyInto(out *MoveLocalBlobs) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(MoveLocalBlobsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(MoveLocalBlobsOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveLocalBlobs.
func (in *MoveLocalBlobs) DeepCopy() *MoveLocalBlobs {
	if in == nil {
		return nil
	}
	out := new(MoveLocalBlobs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *MoveLocalBlobs) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveLocalBlobsOutput) DeepCopyInto(out *MoveLocalBlobsOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveLocalBlobsOutput.
func (in *MoveLocalBlobsOutput) DeepCopy() *MoveLocalBlobsOutput {
	if in == nil {
		return nil
	}
	out := new(MoveLocalBlobsOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveLocalBlobsSpec) DeepCopyInto(out *MoveLocalBlobsSpec) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveLocalBlobsSpec.
func (in *MoveLocalBlobsSpec) DeepCopy() *MoveLocalBlobsSpec {
	if in == nil {
		return nil
	}
	out := new(MoveLocalBlobsSpec)
	in.DeepCopyInto(out)
	return out
}
