package writer

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"ocm.software/open-component-model/bindings/go/generator/universe"
)

const EmbedOutput = "zz_generated.ocm_jsonschema.go"

type TypeEmbedInfo struct {
	Key             universe.TypeKey
	EmbedSchemaPath string
}

// WriteEmbedFileForPackage generates a single embed file for a package.
func WriteEmbedFileForPackage(pkgDir string, pkgName string, types []TypeEmbedInfo) error {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, `//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.


package %s

import (
	_ "embed"
)
`, pkgName)

	// Sort for determinism
	sort.Slice(types, func(i, j int) bool {
		return types[i].Key.TypeName < types[j].Key.TypeName
	})

	// Embed declarations
	for _, ti := range types {
		fmt.Fprintf(&buf, "\n//go:embed %s\n", ti.EmbedSchemaPath)
		fmt.Fprintf(&buf, "var schema%s []byte\n", ti.Key.TypeName)
	}

	// Accessors
	for _, ti := range types {
		fmt.Fprintf(&buf, `

// JSONSchema returns the JSON Schema for %s.
func (%s) JSONSchema() []byte {
	return schema%s
}
`, ti.Key.TypeName, ti.Key.TypeName, ti.Key.TypeName)
	}

	code := buf.Bytes()

	formatted, err := format.Source(code)
	if err != nil {
		fmt.Print(string(code))
		return fmt.Errorf("formatting failed: %w", err)
	}

	outPath := filepath.Join(pkgDir, EmbedOutput)
	return os.WriteFile(outPath, formatted, 0o600)
}
