//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package docs

import (
	_ "embed"
)

//go:embed schemas/Schema.schema.json
var schemaSchema []byte

//go:embed schemas/XDocs.schema.json
var schemaXDocs []byte

// JSONSchema returns the JSON Schema for Schema.
func (Schema) JSONSchema() []byte {
	return schemaSchema
}

// JSONSchema returns the JSON Schema for XDocs.
func (XDocs) JSONSchema() []byte {
	return schemaXDocs
}
