//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package diataxis

import (
	_ "embed"
)

//go:embed schemas/Diataxis.schema.json
var schemaDiataxis []byte

// JSONSchema returns the JSON Schema for Diataxis.
func (Diataxis) JSONSchema() []byte {
	return schemaDiataxis
}
