//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Identity.schema.json
var schemaIdentity []byte

// JSONSchema returns the JSON Schema for Identity.
func (Identity) JSONSchema() []byte {
	return schemaIdentity
}
