version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    ci:
      patterns:
      - "*"
  schedule:
    interval: "daily"
  labels:
  - kind/dependency
  - kind/chore
  - kind/skip-release-notes
  - component/github-actions
- package-ecosystem: "gomod"
  directories:
    - "/cli"
    - "/bindings/go/*"
  groups:
    go:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "daily"
  labels:
  - kind/dependency
  - kind/chore
