//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/OCIRegistryIdentity.schema.json
var schemaOCIRegistryIdentity []byte

// JSONSchema returns the JSON Schema for OCIRegistryIdentity.
func (OCIRegistryIdentity) JSONSchema() []byte {
	return schemaOCIRegistryIdentity
}
