//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/LayerSelector.schema.json
var schemaLayerSelector []byte

//go:embed schemas/Rule.schema.json
var schemaRule []byte

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for LayerSelector.
func (LayerSelector) JSONSchema() []byte {
	return schemaLayerSelector
}

// JSONSchema returns the JSON Schema for Rule.
func (Rule) JSONSchema() []byte {
	return schemaRule
}
