version: '3'

dotenv: ['.env', '.env.local']

includes:
  bindings/go/descriptor:
    optional: true
    taskfile: ./bindings/go/descriptor/Taskfile.yml
    dir: ./bindings/go/descriptor
  bindings/go/runtime:
    optional: true
    taskfile: ./bindings/go/runtime/Taskfile.yml
    dir: ./bindings/go/runtime


tasks:
  test:
    cmds:
      - task: bindings/go/descriptor:test
      - task: bindings/go/runtime:test
