//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/MavenCredentials.schema.json
var schemaMavenCredentials []byte

// JSONSchema returns the JSON Schema for MavenCredentials.
func (MavenCredentials) JSONSchema() []byte {
	return schemaMavenCredentials
}
