//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/S3Identity.schema.json
var schemaS3Identity []byte

// JSONSchema returns the JSON Schema for S3Identity.
func (S3Identity) JSONSchema() []byte {
	return schemaS3Identity
}
