//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/S3BucketIdentity.schema.json
var schemaS3BucketIdentity []byte

// JSONSchema returns the JSON Schema for S3BucketIdentity.
func (S3BucketIdentity) JSONSchema() []byte {
	return schemaS3BucketIdentity
}
