//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package testutils

import (
	_ "embed"
)

//go:embed schemas/MockGetObjectTransformer.schema.json
var schemaMockGetObjectTransformer []byte

//go:embed schemas/MockGetObjectTransformerOutput.schema.json
var schemaMockGetObjectTransformerOutput []byte

//go:embed schemas/MockGetObjectTransformerSpec.schema.json
var schemaMockGetObjectTransformerSpec []byte

// JSONSchema returns the JSON Schema for MockGetObjectTransformer.
func (MockGetObjectTransformer) JSONSchema() []byte {
	return schemaMockGetObjectTransformer
}

// JSONSchema returns the JSON Schema for MockGetObjectTransformerOutput.
func (MockGetObjectTransformerOutput) JSONSchema() []byte {
	return schemaMockGetObjectTransformerOutput
}

// JSONSchema returns the JSON Schema for MockGetObjectTransformerSpec.
func (MockGetObjectTransformerSpec) JSONSchema() []byte {
	return schemaMockGetObjectTransformerSpec
}
