//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ocmtypegen. DO NOT EDIT.

package testutils

import "ocm.software/open-component-model/bindings/go/runtime"

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *MockAddObjectTransformer) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *MockAddObjectTransformer) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *MockCustomSchemaObjectTransformer) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *MockCustomSchemaObjectTransformer) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *MockGetObjectTransformer) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *MockGetObjectTransformer) GetType() runtime.Type {
	return t.Type
}
