//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package testutils

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformer) DeepCopyInto(out *MockGetObjectTransformer) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(MockGetObjectTransformerSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(MockGetObjectTransformerOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformer.
func (in *MockGetObjectTransformer) DeepCopy() *MockGetObjectTransformer {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *MockGetObjectTransformer) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformerOutput) DeepCopyInto(out *MockGetObjectTransformerOutput) {
	*out = *in
	out.Object = in.Object
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformerOutput.
func (in *MockGetObjectTransformerOutput) DeepCopy() *MockGetObjectTransformerOutput {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformerOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformerSpec) DeepCopyInto(out *MockGetObjectTransformerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformerSpec.
func (in *MockGetObjectTransformerSpec) DeepCopy() *MockGetObjectTransformerSpec {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformerSpec)
	in.DeepCopyInto(out)
	return out
}
