//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/NotationIdentity.schema.json
var schemaNotationIdentity []byte

// JSONSchema returns the JSON Schema for NotationIdentity.
func (NotationIdentity) JSONSchema() []byte {
	return schemaNotationIdentity
}
