//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/UTF8.schema.json
var schemaUTF8 []byte

// JSONSchema returns the JSON Schema for UTF8.
func (UTF8) JSONSchema() []byte {
	return schemaUTF8
}
