//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/HelmChartRepositoryIdentity.schema.json
var schemaHelmChartRepositoryIdentity []byte

// JSONSchema returns the JSON Schema for HelmChartRepositoryIdentity.
func (HelmChartRepositoryIdentity) JSONSchema() []byte {
	return schemaHelmChartRepositoryIdentity
}
