version: '3'

includes:
  reuse: ../../../reuse.Taskfile.yml


vars:
  INTEGRATION_TEST_IDENTIFIER: 'Integration'

tasks:
  tmp:
    cmds:
      - mkdir -p tmp
    status:
      - test -d tmp
  test:
    cmds:
      - task: reuse:run-test
        vars:
          SKIP_PATTERN: '{{ .INTEGRATION_TEST_IDENTIFIER }}'
    deps:
      - tmp