version: '3'

includes:
  reuse: ../../../reuse.Taskfile.yml


vars:
  INTEGRATION_TEST_IDENTIFIER: 'Integration'

tasks:
  test:
    cmds:
      - task: reuse:run-test
        vars:
          SKIP_PATTERN: '{{ .INTEGRATION_TEST_IDENTIFIER }}'