run:
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  issues-exit-code: 2


linters:
  enable-all: true
  disable:
    - gomoddirectives  # Replacement statements are not allowed in a library.
                       #   if it has a replace statement, other can't use the
                       #   library at all (go does not allow that)
    - godox            # TODO/FIXME/BUG should not be in the code-base without
                       # a related GitHub issue.
                       #   Added an exclude-rules for that, if a TODO/FIXME/BUG
                       #   line has an URL on the line, it counts as valid mark.
    - err113         # Do not define dynamic errors with Errorf.

    - gochecknoglobals
    - lll
    - paralleltest
    - wsl
    - inamedparam
    - mnd
    - ireturn
    - varnamelen
    - nlreturn
    - nonamedreturns
    - gochecknoinits
    - exhaustruct      # Doesn't really make sense.
    - exhaustive       # Doesn't really make sense.
    - goimports        # gci handles imports anyway
    - tenv           # Replaced by usetesting.
    - godot

linters-settings:
  wrapcheck:
    extra-ignore-sigs:
      - .Unmarshal(
      - .Marshal(
      - (*github.com/spf13/pflag.FlagSet).GetString(
      - ocm.software/open-component-model
  revive:
    rules:
      - name: redefines-builtin-id
        disabled: true
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - ocm.software/open-component-model
          - sigs.k8s.io/yaml # json + yaml conversion is done the same way as k8s
          - github.com/cyberphone/json-canonicalization # we need canonicalization
          - github.com/opencontainers/go-digest # we need OCI style digests
          - golang.org/x/sync/errgroup # errgroups are ok
          - github.com/opencontainers/image-spec # oci image spec is okay
          - github.com/nlepage/go-tarfs # tar based filesystems are important for us
          - github.com/spf13/cobra # for building a CLI
          - github.com/spf13/pflag # for building a CLI
  gci:
    sections:
      - standard
      - blank
      - dot
      - default
      - prefix(ocm.software/open-component-model)
    custom-order: true
  cyclop:
    max-complexity: 15
    skip-tests: true
  lll:
    line-length: 120
  recvcheck:
    exclusions:
      - "*.UnmarshalJSON" # UnmarshalJSON always needs pointer values to do proper value assignments
  perfsprint:
    strconcat: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

