default: true

MD013: false #Line length - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md013
MD033: false #Inline HTML - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md033
MD024:
  siblings_only: true #Multiple headers with the same content
MD009: false #no-trailing-spaces Trailing spaces
MD004: false #Unordered list style
MD031: false #Fenced code blocks should be surrounded by blank lines
MD036: false #No emphasis added