//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddGitResource) DeepCopyInto(out *AddGitResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(AddGitResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(AddGitResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddGitResource.
func (in *AddGitResource) DeepCopy() *AddGitResource {
	if in == nil {
		return nil
	}
	out := new(AddGitResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *AddGitResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddGitResourceOutput) DeepCopyInto(out *AddGitResourceOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddGitResourceOutput.
func (in *AddGitResourceOutput) DeepCopy() *AddGitResourceOutput {
	if in == nil {
		return nil
	}
	out := new(AddGitResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddGitResourceSpec) DeepCopyInto(out *AddGitResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddGitResourceSpec.
func (in *AddGitResourceSpec) DeepCopy() *AddGitResourceSpec {
	if in == nil {
		return nil
	}
	out := new(AddGitResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitResource) DeepCopyInto(out *GetGitResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetGitResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetGitResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitResource.
func (in *GetGitResource) DeepCopy() *GetGitResource {
	if in == nil {
		return nil
	}
	out := new(GetGitResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetGitResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitResourceOutput) DeepCopyInto(out *GetGitResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitResourceOutput.
func (in *GetGitResourceOutput) DeepCopy() *GetGitResourceOutput {
	if in == nil {
		return nil
	}
	out := new(GetGitResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitResourceSpec) DeepCopyInto(out *GetGitResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitResourceSpec.
func (in *GetGitResourceSpec) DeepCopy() *GetGitResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GetGitResourceSpec)
	in.DeepCopyInto(out)
	return out
}
