//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/ConvertHelmToOCI.schema.json
var schemaConvertHelmToOCI []byte

//go:embed schemas/ConvertHelmToOCIOutput.schema.json
var schemaConvertHelmToOCIOutput []byte

//go:embed schemas/ConvertHelmToOCISpec.schema.json
var schemaConvertHelmToOCISpec []byte

//go:embed schemas/GetHelmChart.schema.json
var schemaGetHelmChart []byte

//go:embed schemas/GetHelmChartOutput.schema.json
var schemaGetHelmChartOutput []byte

//go:embed schemas/GetHelmChartSpec.schema.json
var schemaGetHelmChartSpec []byte

// JSONSchema returns the JSON Schema for ConvertHelmToOCI.
func (ConvertHelmToOCI) JSONSchema() []byte {
	return schemaConvertHelmToOCI
}

// JSONSchema returns the JSON Schema for ConvertHelmToOCIOutput.
func (ConvertHelmToOCIOutput) JSONSchema() []byte {
	return schemaConvertHelmToOCIOutput
}

// JSONSchema returns the JSON Schema for ConvertHelmToOCISpec.
func (ConvertHelmToOCISpec) JSONSchema() []byte {
	return schemaConvertHelmToOCISpec
}

// JSONSchema returns the JSON Schema for GetHelmChart.
func (GetHelmChart) JSONSchema() []byte {
	return schemaGetHelmChart
}

// JSONSchema returns the JSON Schema for GetHelmChartOutput.
func (GetHelmChartOutput) JSONSchema() []byte {
	return schemaGetHelmChartOutput
}

// JSONSchema returns the JSON Schema for GetHelmChartSpec.
func (GetHelmChartSpec) JSONSchema() []byte {
	return schemaGetHelmChartSpec
}
