//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package transformations

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadComponentTransformation) DeepCopyInto(out *DownloadComponentTransformation) {
	*out = *in
	out.TransformationMeta = in.TransformationMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadComponentTransformation.
func (in *DownloadComponentTransformation) DeepCopy() *DownloadComponentTransformation {
	if in == nil {
		return nil
	}
	out := new(DownloadComponentTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DownloadComponentTransformation) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadComponentTransformationSpec) DeepCopyInto(out *DownloadComponentTransformationSpec) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadComponentTransformationSpec.
func (in *DownloadComponentTransformationSpec) DeepCopy() *DownloadComponentTransformationSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadComponentTransformationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadComponentTransformation) DeepCopyInto(out *UploadComponentTransformation) {
	*out = *in
	out.TransformationMeta = in.TransformationMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadComponentTransformation.
func (in *UploadComponentTransformation) DeepCopy() *UploadComponentTransformation {
	if in == nil {
		return nil
	}
	out := new(UploadComponentTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *UploadComponentTransformation) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
