//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/SignConfig.schema.json
var schemaSignConfig []byte

//go:embed schemas/VerifyConfig.schema.json
var schemaVerifyConfig []byte

// JSONSchema returns the JSON Schema for SignConfig.
func (SignConfig) JSONSchema() []byte {
	return schemaSignConfig
}

// JSONSchema returns the JSON Schema for VerifyConfig.
func (VerifyConfig) JSONSchema() []byte {
	return schemaVerifyConfig
}
