//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Wget.schema.json
var schemaWget []byte

// JSONSchema returns the JSON Schema for Wget.
func (Wget) JSONSchema() []byte {
	return schemaWget
}
