//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package repositoryupload

import (
	_ "embed"
)

//go:embed schemas/ComponentVersion.schema.json
var schemaComponentVersion []byte

//go:embed schemas/Output.schema.json
var schemaOutput []byte

//go:embed schemas/Spec.schema.json
var schemaSpec []byte

// JSONSchema returns the JSON Schema for ComponentVersion.
func (ComponentVersion) JSONSchema() []byte {
	return schemaComponentVersion
}

// JSONSchema returns the JSON Schema for Output.
func (Output) JSONSchema() []byte {
	return schemaOutput
}

// JSONSchema returns the JSON Schema for Spec.
func (Spec) JSONSchema() []byte {
	return schemaSpec
}
