//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package oci

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadComponentTransformation) DeepCopyInto(out *DownloadComponentTransformation) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DownloadComponentTransformationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(DownloadComponentTransformationOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadComponentTransformation.
func (in *DownloadComponentTransformation) DeepCopy() *DownloadComponentTransformation {
	if in == nil {
		return nil
	}
	out := new(DownloadComponentTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DownloadComponentTransformation) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadComponentTransformationOutput) DeepCopyInto(out *DownloadComponentTransformationOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadComponentTransformationOutput.
func (in *DownloadComponentTransformationOutput) DeepCopy() *DownloadComponentTransformationOutput {
	if in == nil {
		return nil
	}
	out := new(DownloadComponentTransformationOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadComponentTransformationSpec) DeepCopyInto(out *DownloadComponentTransformationSpec) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadComponentTransformationSpec.
func (in *DownloadComponentTransformationSpec) DeepCopy() *DownloadComponentTransformationSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadComponentTransformationSpec)
	in.DeepCopyInto(out)
	return out
}
