//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/DownloadS3Resource.schema.json
var schemaDownloadS3Resource []byte

//go:embed schemas/DownloadS3ResourceOutput.schema.json
var schemaDownloadS3ResourceOutput []byte

//go:embed schemas/DownloadS3ResourceSpec.schema.json
var schemaDownloadS3ResourceSpec []byte

// JSONSchema returns the JSON Schema for DownloadS3Resource.
func (DownloadS3Resource) JSONSchema() []byte {
	return schemaDownloadS3Resource
}

// JSONSchema returns the JSON Schema for DownloadS3ResourceOutput.
func (DownloadS3ResourceOutput) JSONSchema() []byte {
	return schemaDownloadS3ResourceOutput
}

// JSONSchema returns the JSON Schema for DownloadS3ResourceSpec.
func (DownloadS3ResourceSpec) JSONSchema() []byte {
	return schemaDownloadS3ResourceSpec
}
