//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.35. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersion) DeepCopyInto(out *CTFAddComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFAddComponentVersionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFAddComponentVersionOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersion.
func (in *CTFAddComponentVersion) DeepCopy() *CTFAddComponentVersion {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFAddComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersionOutput) DeepCopyInto(out *CTFAddComponentVersionOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersionOutput.
func (in *CTFAddComponentVersionOutput) DeepCopy() *CTFAddComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersionSpec) DeepCopyInto(out *CTFAddComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersionSpec.
func (in *CTFAddComponentVersionSpec) DeepCopy() *CTFAddComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersion) DeepCopyInto(out *CTFGetComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFGetComponentVersionSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFGetComponentVersionOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersion.
func (in *CTFGetComponentVersion) DeepCopy() *CTFGetComponentVersion {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFGetComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersionOutput) DeepCopyInto(out *CTFGetComponentVersionOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersionOutput.
func (in *CTFGetComponentVersionOutput) DeepCopy() *CTFGetComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersionSpec) DeepCopyInto(out *CTFGetComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersionSpec.
func (in *CTFGetComponentVersionSpec) DeepCopy() *CTFGetComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersion) DeepCopyInto(out *OCIAddComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIAddComponentVersionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIAddComponentVersionOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersion.
func (in *OCIAddComponentVersion) DeepCopy() *OCIAddComponentVersion {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIAddComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersionOutput) DeepCopyInto(out *OCIAddComponentVersionOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersionOutput.
func (in *OCIAddComponentVersionOutput) DeepCopy() *OCIAddComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersionSpec) DeepCopyInto(out *OCIAddComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersionSpec.
func (in *OCIAddComponentVersionSpec) DeepCopy() *OCIAddComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersion) DeepCopyInto(out *OCIGetComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIGetComponentVersionSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIGetComponentVersionOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersion.
func (in *OCIGetComponentVersion) DeepCopy() *OCIGetComponentVersion {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIGetComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersionOutput) DeepCopyInto(out *OCIGetComponentVersionOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersionOutput.
func (in *OCIGetComponentVersionOutput) DeepCopy() *OCIGetComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersionSpec) DeepCopyInto(out *OCIGetComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersionSpec.
func (in *OCIGetComponentVersionSpec) DeepCopy() *OCIGetComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}
