//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/CTFAddComponentVersion.schema.json
var schemaCTFAddComponentVersion []byte

//go:embed schemas/CTFAddComponentVersionOutput.schema.json
var schemaCTFAddComponentVersionOutput []byte

//go:embed schemas/CTFAddComponentVersionSpec.schema.json
var schemaCTFAddComponentVersionSpec []byte

//go:embed schemas/CTFGetComponentVersion.schema.json
var schemaCTFGetComponentVersion []byte

//go:embed schemas/CTFGetComponentVersionOutput.schema.json
var schemaCTFGetComponentVersionOutput []byte

//go:embed schemas/CTFGetComponentVersionSpec.schema.json
var schemaCTFGetComponentVersionSpec []byte

//go:embed schemas/OCIAddComponentVersion.schema.json
var schemaOCIAddComponentVersion []byte

//go:embed schemas/OCIAddComponentVersionOutput.schema.json
var schemaOCIAddComponentVersionOutput []byte

//go:embed schemas/OCIAddComponentVersionSpec.schema.json
var schemaOCIAddComponentVersionSpec []byte

//go:embed schemas/OCIGetComponentVersion.schema.json
var schemaOCIGetComponentVersion []byte

//go:embed schemas/OCIGetComponentVersionOutput.schema.json
var schemaOCIGetComponentVersionOutput []byte

//go:embed schemas/OCIGetComponentVersionSpec.schema.json
var schemaOCIGetComponentVersionSpec []byte

// JSONSchema returns the JSON Schema for CTFAddComponentVersion.
func (CTFAddComponentVersion) JSONSchema() []byte {
	return schemaCTFAddComponentVersion
}

// JSONSchema returns the JSON Schema for CTFAddComponentVersionOutput.
func (CTFAddComponentVersionOutput) JSONSchema() []byte {
	return schemaCTFAddComponentVersionOutput
}

// JSONSchema returns the JSON Schema for CTFAddComponentVersionSpec.
func (CTFAddComponentVersionSpec) JSONSchema() []byte {
	return schemaCTFAddComponentVersionSpec
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersion.
func (CTFGetComponentVersion) JSONSchema() []byte {
	return schemaCTFGetComponentVersion
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersionOutput.
func (CTFGetComponentVersionOutput) JSONSchema() []byte {
	return schemaCTFGetComponentVersionOutput
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersionSpec.
func (CTFGetComponentVersionSpec) JSONSchema() []byte {
	return schemaCTFGetComponentVersionSpec
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersion.
func (OCIAddComponentVersion) JSONSchema() []byte {
	return schemaOCIAddComponentVersion
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersionOutput.
func (OCIAddComponentVersionOutput) JSONSchema() []byte {
	return schemaOCIAddComponentVersionOutput
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersionSpec.
func (OCIAddComponentVersionSpec) JSONSchema() []byte {
	return schemaOCIAddComponentVersionSpec
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersion.
func (OCIGetComponentVersion) JSONSchema() []byte {
	return schemaOCIGetComponentVersion
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersionOutput.
func (OCIGetComponentVersionOutput) JSONSchema() []byte {
	return schemaOCIGetComponentVersionOutput
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersionSpec.
func (OCIGetComponentVersionSpec) JSONSchema() []byte {
	return schemaOCIGetComponentVersionSpec
}
