# Use multi-stage builds to copy certs from a minimal base image.
# Debian uses the Mozilla CA bundle which contains a maximum number of trusted CAs.
FROM --platform=$BUILDPLATFORM debian:bookworm-slim@sha256:936abff852736f951dab72d91a1b6337cf04217b2a77a5eaadc7c0f2f1ec1758 AS certs
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

FROM scratch
ARG TARGETOS
ARG TARGETARCH
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY tmp/bin/ocm-${TARGETOS}-${TARGETARCH} /ocm
ENTRYPOINT ["/ocm"]
