//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GetPyPIArtifact.schema.json
var schemaGetPyPIArtifact []byte

//go:embed schemas/GetPyPIArtifactOutput.schema.json
var schemaGetPyPIArtifactOutput []byte

//go:embed schemas/GetPyPIArtifactSpec.schema.json
var schemaGetPyPIArtifactSpec []byte

// JSONSchema returns the JSON Schema for GetPyPIArtifact.
func (GetPyPIArtifact) JSONSchema() []byte {
	return schemaGetPyPIArtifact
}

// JSONSchema returns the JSON Schema for GetPyPIArtifactOutput.
func (GetPyPIArtifactOutput) JSONSchema() []byte {
	return schemaGetPyPIArtifactOutput
}

// JSONSchema returns the JSON Schema for GetPyPIArtifactSpec.
func (GetPyPIArtifactSpec) JSONSchema() []byte {
	return schemaGetPyPIArtifactSpec
}
