//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetPyPIArtifact) DeepCopyInto(out *GetPyPIArtifact) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetPyPIArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetPyPIArtifactOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetPyPIArtifact.
func (in *GetPyPIArtifact) DeepCopy() *GetPyPIArtifact {
	if in == nil {
		return nil
	}
	out := new(GetPyPIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetPyPIArtifact) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetPyPIArtifactOutput) DeepCopyInto(out *GetPyPIArtifactOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetPyPIArtifactOutput.
func (in *GetPyPIArtifactOutput) DeepCopy() *GetPyPIArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(GetPyPIArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetPyPIArtifactSpec) DeepCopyInto(out *GetPyPIArtifactSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetPyPIArtifactSpec.
func (in *GetPyPIArtifactSpec) DeepCopy() *GetPyPIArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(GetPyPIArtifactSpec)
	in.DeepCopyInto(out)
	return out
}
