//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/S3Bucket.schema.json
var schemaS3Bucket []byte

// JSONSchema returns the JSON Schema for S3Bucket.
func (S3Bucket) JSONSchema() []byte {
	return schemaS3Bucket
}
