//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package test

import (
	_ "embed"
)

//go:embed schemas/SampleType.schema.json
var schemaSampleType []byte

// JSONSchema returns the JSON Schema for SampleType.
func (SampleType) JSONSchema() []byte {
	return schemaSampleType
}
