//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by typegen. DO NOT EDIT.

package test

import "ocm.software/open-component-model/bindings/go/runtime"

func (t *SampleType) SetType(typ runtime.Type) {
	t.Type = typ
}

func (t *SampleType) GetType() runtime.Type {
	return t.Type
}
