//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/NotationCredentials.schema.json
var schemaNotationCredentials []byte

// JSONSchema returns the JSON Schema for NotationCredentials.
func (NotationCredentials) JSONSchema() []byte {
	return schemaNotationCredentials
}
