//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package spec

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *Config) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploaderConfig) DeepCopyInto(out *UploaderConfig) {
	*out = *in
	out.Type = in.Type
	out.Match = in.Match
	if in.Stream != nil {
		in, out := &in.Stream, &out.Stream
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploaderConfig.
func (in *UploaderConfig) DeepCopy() *UploaderConfig {
	if in == nil {
		return nil
	}
	out := new(UploaderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *UploaderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploaderMatch) DeepCopyInto(out *UploaderMatch) {
	*out = *in
	out.AccessType = in.AccessType
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploaderMatch.
func (in *UploaderMatch) DeepCopy() *UploaderMatch {
	if in == nil {
		return nil
	}
	out := new(UploaderMatch)
	in.DeepCopyInto(out)
	return out
}
