version: '3'

includes:
  reuse: ../../../reuse.Taskfile.yml


tasks:
  tmp:
    cmds:
      - mkdir -p tmp
    status:
      - test -d tmp
  test:
    deps: [test/unit, test/bench]
  test/unit:
    cmds:
      - task: reuse:run-test
    deps:
      - tmp
  test/bench:
    cmds:
      - go test -v -bench=./...
    deps:
      - tmp