version: '3'

includes:
  reuse: ../../../reuse.Taskfile.yml


tasks:
  test:
    deps: [test/unit, test/bench]
  test/unit:
    cmds:
      - task: reuse:run-go-test
  test/bench:
    cmds:
      - task: reuse:run-go-test
        vars:
          GO_TEST_FLAGS: -bench=./...
          PACKAGES: '.'