//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/PyPI.schema.json
var schemaPyPI []byte

// JSONSchema returns the JSON Schema for PyPI.
func (PyPI) JSONSchema() []byte {
	return schemaPyPI
}
