//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyPI) DeepCopyInto(out *PyPI) {
	*out = *in
	out.Type = in.Type
	if in.Distributions != nil {
		in, out := &in.Distributions, &out.Distributions
		*out = make([]Distribution, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyPI.
func (in *PyPI) DeepCopy() *PyPI {
	if in == nil {
		return nil
	}
	out := new(PyPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *PyPI) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
