package e2e

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

var (
	// Global TestEnv
	env *TestEnv
)

// TestEnv holds the configuration and shared resources for the test execution.
type TestEnv struct {
	Config   *Config
	Registry RegistryProvider
	Cluster  ClusterProvider
	CLI      CLIProvider

	// Paths
	WorkDir  string
	CertsDir string
}

// TestMain acts as the global entry point for the test suite.
func TestMain(m *testing.M) {
	// Parse Flags
	cfg := ParseConfig()

	// Initialize TestEnv
	workDir, err := os.MkdirTemp("", "ocm-e2e-*")
	if err != nil {
		fmt.Printf("Failed to create workdir: %v\n", err)
		os.Exit(1)
	}
	// Defer cleanup handled in Teardown

	certsDir := filepath.Join(workDir, "certs")
	if err := os.MkdirAll(certsDir, 0755); err != nil {
		fmt.Printf("Failed to create certs dir: %v\n", err)
		os.Exit(1)
	}

	env = &TestEnv{
		Config:   cfg,
		WorkDir:  workDir,
		CertsDir: certsDir,
		Registry: NewZotProvider(cfg, workDir, certsDir),
		Cluster:  NewKindProvider(cfg, workDir),
		CLI:      NewOCMCLIProvider(cfg, workDir, certsDir),
	}

	ctx := context.Background()

	// Setup Infrastructure
	fmt.Println("Setting up Test Infrastructure...")
	if err := env.Setup(ctx); err != nil {
		fmt.Printf("Failed to setup test environment: %v\n", err)
		env.Teardown(ctx)
		os.Exit(1)
	}

	// Run Tests
	code := m.Run()

	// Teardown
	fmt.Println("Tearing down Test Infrastructure...")
	if err := env.Teardown(ctx); err != nil {
		fmt.Printf("Failed to teardown: %v\n", err)
	}
	os.RemoveAll(workDir)

	os.Exit(code)
}

func (e *TestEnv) Setup(ctx context.Context) error {
	// Parallel setup could be an option, but sequential for now to avoid complexity
	if err := e.Registry.Setup(ctx); err != nil {
		return fmt.Errorf("registry setup failed: %w", err)
	}
	if err := e.Cluster.Setup(ctx); err != nil {
		return fmt.Errorf("cluster setup failed: %w", err)
	}
	// CLI depends on registry certs and possibly cluster config?
	// CLI runner extracts binary and mounts certs.
	// Certs are generated by Registry provider.
	// So Registry MUST be setup before CLI.
	if err := e.CLI.Setup(ctx); err != nil {
		return fmt.Errorf("cli provider setup failed: %w", err)
	}
	return nil
}

func (e *TestEnv) Teardown(ctx context.Context) error {
	var errs []error
	if err := e.CLI.Teardown(ctx); err != nil {
		errs = append(errs, err)
	}
	if err := e.Registry.Teardown(ctx); err != nil {
		errs = append(errs, err)
	}
	if err := e.Cluster.Teardown(ctx); err != nil {
		errs = append(errs, err)
	}
	if len(errs) > 0 {
		return fmt.Errorf("teardown errors: %v", errs)
	}
	return nil
}

// NewTestEnv creates a new TestEnv with the parsed configuration.
// (Deprecated/Unused in new global model, but keeping as helper if needed or removing)
// We remove it to avoid confusion.

// TestMeta defines metadata for a test, including labels and description.
type TestMeta struct {
	ID          string // Optional unique ID
	Description string
	Labels      map[string]string
}

// Bind binds the test metadata to the current test execution.
// It logs the test description.
func (m *TestMeta) Bind(t *testing.T) {
	t.Logf("Test: %s", t.Name())
	if m.Description != "" {
		t.Logf("Description: %s", m.Description)
	}
}

// HasLabel checks if the metadata contains the specified label with the given value.
func (m *TestMeta) HasLabel(key, value string) bool {
	if m.Labels == nil {
		return false
	}
	v, ok := m.Labels[key]
	return ok && v == value
}

// RequireLabel skips the test if the metadata does not contain the specified label with the given value.
func (m *TestMeta) RequireLabel(t *testing.T, key, value string) {
	if !m.HasLabel(key, value) {
		t.Skipf("Skipping test %s: required label %s=%s not found", t.Name(), key, value)
	}
}

// Common Labels
const (
	LabelTestKind    = "test-kind"
	ValueConformance = "conformance"
	ValueE2E         = "e2e"
)

// NewConformanceMeta creates a TestMeta for a conformance test.
func NewConformanceMeta(id, description string) *TestMeta {
	return &TestMeta{
		ID:          id,
		Description: description,
		Labels: map[string]string{
			LabelTestKind: ValueConformance,
		},
	}
}
