//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.35. DO NOT EDIT.

package e2e

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryCLIProviderSpec) DeepCopyInto(out *BinaryCLIProviderSpec) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryCLIProviderSpec.
func (in *BinaryCLIProviderSpec) DeepCopy() *BinaryCLIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(BinaryCLIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *BinaryCLIProviderSpec) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLIProviderConfig) DeepCopyInto(out *CLIProviderConfig) {
	*out = *in
	out.Type = in.Type
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLIProviderConfig.
func (in *CLIProviderConfig) DeepCopy() *CLIProviderConfig {
	if in == nil {
		return nil
	}
	out := new(CLIProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CLIProviderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfig) DeepCopyInto(out *ClusterProviderConfig) {
	*out = *in
	out.Type = in.Type
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfig.
func (in *ClusterProviderConfig) DeepCopy() *ClusterProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ClusterProviderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCLIProviderSpec) DeepCopyInto(out *ImageCLIProviderSpec) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCLIProviderSpec.
func (in *ImageCLIProviderSpec) DeepCopy() *ImageCLIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ImageCLIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ImageCLIProviderSpec) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindProviderSpec) DeepCopyInto(out *KindProviderSpec) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindProviderSpec.
func (in *KindProviderSpec) DeepCopy() *KindProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KindProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *KindProviderSpec) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryProviderConfig) DeepCopyInto(out *RegistryProviderConfig) {
	*out = *in
	out.Type = in.Type
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryProviderConfig.
func (in *RegistryProviderConfig) DeepCopy() *RegistryProviderConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *RegistryProviderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZotProviderSpec) DeepCopyInto(out *ZotProviderSpec) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZotProviderSpec.
func (in *ZotProviderSpec) DeepCopy() *ZotProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ZotProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ZotProviderSpec) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
