//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ocmtypegen. DO NOT EDIT.

package e2e

import "ocm.software/open-component-model/bindings/go/runtime"

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *RegistryProviderConfig) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *RegistryProviderConfig) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *ClusterProviderConfig) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *ClusterProviderConfig) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *CLIProviderConfig) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *CLIProviderConfig) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *ZotProviderSpec) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *ZotProviderSpec) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *KindProviderSpec) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *KindProviderSpec) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *ImageCLIProviderSpec) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *ImageCLIProviderSpec) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *BinaryCLIProviderSpec) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *BinaryCLIProviderSpec) GetType() runtime.Type {
	return t.Type
}
