//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/WgetCredentials.schema.json
var schemaWgetCredentials []byte

// JSONSchema returns the JSON Schema for WgetCredentials.
func (WgetCredentials) JSONSchema() []byte {
	return schemaWgetCredentials
}
