# OCM Repository pointing to local air-gapped registry
apiVersion: delivery.ocm.software/v1alpha1
kind: Repository
metadata:
  name: sovereign-repo
  namespace: sovereign-product
spec:
  repositorySpec:
    baseUrl: http://registry:5000
    type: OCIRegistry
  interval: 10m