//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/S3Credentials.schema.json
var schemaS3Credentials []byte

// JSONSchema returns the JSON Schema for S3Credentials.
func (S3Credentials) JSONSchema() []byte {
	return schemaS3Credentials
}
