//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Dir.schema.json
var schemaDir []byte

// JSONSchema returns the JSON Schema for Dir.
func (Dir) JSONSchema() []byte {
	return schemaDir
}
