//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GetMavenArtifact.schema.json
var schemaGetMavenArtifact []byte

//go:embed schemas/GetMavenArtifactOutput.schema.json
var schemaGetMavenArtifactOutput []byte

//go:embed schemas/GetMavenArtifactSpec.schema.json
var schemaGetMavenArtifactSpec []byte

// JSONSchema returns the JSON Schema for GetMavenArtifact.
func (GetMavenArtifact) JSONSchema() []byte {
	return schemaGetMavenArtifact
}

// JSONSchema returns the JSON Schema for GetMavenArtifactOutput.
func (GetMavenArtifactOutput) JSONSchema() []byte {
	return schemaGetMavenArtifactOutput
}

// JSONSchema returns the JSON Schema for GetMavenArtifactSpec.
func (GetMavenArtifactSpec) JSONSchema() []byte {
	return schemaGetMavenArtifactSpec
}
