//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetMavenArtifact) DeepCopyInto(out *GetMavenArtifact) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetMavenArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetMavenArtifactOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMavenArtifact.
func (in *GetMavenArtifact) DeepCopy() *GetMavenArtifact {
	if in == nil {
		return nil
	}
	out := new(GetMavenArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetMavenArtifact) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetMavenArtifactOutput) DeepCopyInto(out *GetMavenArtifactOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMavenArtifactOutput.
func (in *GetMavenArtifactOutput) DeepCopy() *GetMavenArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(GetMavenArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetMavenArtifactSpec) DeepCopyInto(out *GetMavenArtifactSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMavenArtifactSpec.
func (in *GetMavenArtifactSpec) DeepCopy() *GetMavenArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(GetMavenArtifactSpec)
	in.DeepCopyInto(out)
	return out
}
