//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/Duration.schema.json
var schemaDuration []byte

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for Duration.
func (Duration) JSONSchema() []byte {
	return schemaDuration
}
