version: '3'

includes:
  reuse: ../../../../reuse.Taskfile.yml

vars:
  INTEGRATION_TEST_IDENTIFIER: 'Integration'

tasks:
  test/integration:
    cmds:
      - task: reuse:run-test
        vars:
          GO_TEST_FLAGS: '-run "{{ .INTEGRATION_TEST_IDENTIFIER }}"'