//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/NPM.schema.json
var schemaNPM []byte

// JSONSchema returns the JSON Schema for NPM.
func (NPM) JSONSchema() []byte {
	return schemaNPM
}
