//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package oci

import (
	_ "embed"
)

//go:embed schemas/Repository.schema.json
var schemaRepository []byte

// JSONSchema returns the JSON Schema for Repository.
func (Repository) JSONSchema() []byte {
	return schemaRepository
}
