version: '3'


tasks:
  tmp:
    cmds:
      - mkdir -p tmp
    status:
      - test -d tmp
  test:
    sources:
      - ./**/*.go
      - ./go.mod
      - ./go.sum
    cmds:
      - go test -v -race -coverprofile=tmp/coverage.out ./...
    deps:
      - tmp