//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/GitBasicCredentials.schema.json
var schemaGitBasicCredentials []byte

//go:embed schemas/GitBearerCredentials.schema.json
var schemaGitBearerCredentials []byte

//go:embed schemas/GitCredentials.schema.json
var schemaGitCredentials []byte

//go:embed schemas/GitSSHCredentials.schema.json
var schemaGitSSHCredentials []byte

// JSONSchema returns the JSON Schema for GitBasicCredentials.
func (GitBasicCredentials) JSONSchema() []byte {
	return schemaGitBasicCredentials
}

// JSONSchema returns the JSON Schema for GitBearerCredentials.
func (GitBearerCredentials) JSONSchema() []byte {
	return schemaGitBearerCredentials
}

// JSONSchema returns the JSON Schema for GitCredentials.
func (GitCredentials) JSONSchema() []byte {
	return schemaGitCredentials
}

// JSONSchema returns the JSON Schema for GitSSHCredentials.
func (GitSSHCredentials) JSONSchema() []byte {
	return schemaGitSSHCredentials
}
