//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ocmtypegen. DO NOT EDIT.

package v1

import "ocm.software/open-component-model/bindings/go/runtime"

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *GitCredentials) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *GitCredentials) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *GitHTTPSCredentials) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *GitHTTPSCredentials) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *GitBearerCredentials) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *GitBearerCredentials) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *GitSSHCredentials) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *GitSSHCredentials) GetType() runtime.Type {
	return t.Type
}
