//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/File.schema.json
var schemaFile []byte

// JSONSchema returns the JSON Schema for File.
func (File) JSONSchema() []byte {
	return schemaFile
}
