//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/GitHub.schema.json
var schemaGitHub []byte

// JSONSchema returns the JSON Schema for GitHub.
func (GitHub) JSONSchema() []byte {
	return schemaGitHub
}
