//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Maven.schema.json
var schemaMaven []byte

// JSONSchema returns the JSON Schema for Maven.
func (Maven) JSONSchema() []byte {
	return schemaMaven
}
