//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maven) DeepCopyInto(out *Maven) {
	*out = *in
	out.Type = in.Type
	if in.Classifier != nil {
		in, out := &in.Classifier, &out.Classifier
		*out = new(string)
		**out = **in
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(string)
		**out = **in
	}
	if in.MediaType != nil {
		in, out := &in.MediaType, &out.MediaType
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maven.
func (in *Maven) DeepCopy() *Maven {
	if in == nil {
		return nil
	}
	out := new(Maven)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *Maven) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
