//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/TSAIdentity.schema.json
var schemaTSAIdentity []byte

// JSONSchema returns the JSON Schema for TSAIdentity.
func (TSAIdentity) JSONSchema() []byte {
	return schemaTSAIdentity
}
