//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/HelmHTTPCredentials.schema.json
var schemaHelmHTTPCredentials []byte

// JSONSchema returns the JSON Schema for HelmHTTPCredentials.
func (HelmHTTPCredentials) JSONSchema() []byte {
	return schemaHelmHTTPCredentials
}
