//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/NPMRegistryIdentity.schema.json
var schemaNPMRegistryIdentity []byte

// JSONSchema returns the JSON Schema for NPMRegistryIdentity.
func (NPMRegistryIdentity) JSONSchema() []byte {
	return schemaNPMRegistryIdentity
}
