//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/SigstoreCredentials.schema.json
var schemaSigstoreCredentials []byte

// JSONSchema returns the JSON Schema for SigstoreCredentials.
func (SigstoreCredentials) JSONSchema() []byte {
	return schemaSigstoreCredentials
}
