//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/NPMCredentials.schema.json
var schemaNPMCredentials []byte

// JSONSchema returns the JSON Schema for NPMCredentials.
func (NPMCredentials) JSONSchema() []byte {
	return schemaNPMCredentials
}
