version: '3'

tasks:
  tmp:
    cmds:
      - mkdir -p tmp
    status:
      - test -d tmp
  test:
    deps:
      - tmp
    desc: "Run all Generator tests"
    cmds:
      - task: ocmtypegen/test
      - go test -v -coverprofile=tmp/coverage.out ./...

  ocmtypegen/install:
    desc: "Install {{.PKG}} into tmp ({{ .ROOT_DIR }}/tmp/bin) if not already present"
    vars:
      PKG: '{{ .TASKFILE_DIR }}/ocmtypegen/...'
    env:
      GOBIN: '{{ .ROOT_DIR }}/tmp/bin'
    cmds:
      - go install {{ .PKG }}

  ocmtypegen/generate:
    deps: ["ocmtypegen/install"]
    desc: "Run Type OCM Type Code Generation in the Project"
    cmds: [ task: ocmtypegen/concurrent ]

  ocmtypegen/concurrent:
    internal: true
    deps:
      - for: { var: GO_MODULES }
        task: 'ocmtypegen/module'
        vars: { ITEM: '{{ .ITEM }}' }

  ocmtypegen/module:
    internal: true
    silent: true
    prefix: '{{.ITEM}}'
    cmd: '{{ .ROOT_DIR }}/tmp/bin/ocmtypegen {{ .ROOT_DIR }}/{{.ITEM}}'

  ocmtypegen/test:
    desc: "Run OCM Type Generation test"
    cmds:
      - cmd: 'go run {{ .TASKFILE_DIR }}/ocmtypegen/... {{ .TASKFILE_DIR }}/ocmtypegen/test'

  jsonschemagen/install:
    desc: "Install {{.PKG}} into tmp ({{ .ROOT_DIR }}/tmp/bin) if not already present"
    vars:
      PKG: '{{ .TASKFILE_DIR }}/jsonschemagen/...'
    env:
      GOBIN: '{{ .ROOT_DIR }}/tmp/bin'
    cmds:
      - go install {{ .PKG }}

  jsonschemagen/generate:
    deps: ["jsonschemagen/install"]
    desc: "Run Type OCM JSON Schema Generation in the Project"
    cmds: [ task: jsonschemagen/concurrent ]

  jsonschemagen/concurrent:
    internal: true
    deps:
      - for: { var: GO_MODULES }
        task: 'jsonschemagen/module'
        vars: { ITEM: '{{ .ITEM }}' }

  jsonschemagen/module:
    internal: true
    silent: true
    prefix: '{{.ITEM}}'
    cmd: '{{ .ROOT_DIR }}/tmp/bin/jsonschemagen {{ .ROOT_DIR }}/{{.ITEM}}'

  jsonschemagen/test:
    desc: "Run OCM JSON Schema Generation test"
    cmds:
      - cmd: 'go run {{ .TASKFILE_DIR }}/jsonschemagen/... {{ .TASKFILE_DIR }}/jsonschemagen/test'