//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/PyPICredentials.schema.json
var schemaPyPICredentials []byte

// JSONSchema returns the JSON Schema for PyPICredentials.
func (PyPICredentials) JSONSchema() []byte {
	return schemaPyPICredentials
}
