//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/OCIImage.schema.json
var schemaOCIImage []byte

//go:embed schemas/OCIImageLayer.schema.json
var schemaOCIImageLayer []byte

// JSONSchema returns the JSON Schema for OCIImage.
func (OCIImage) JSONSchema() []byte {
	return schemaOCIImage
}

// JSONSchema returns the JSON Schema for OCIImageLayer.
func (OCIImageLayer) JSONSchema() []byte {
	return schemaOCIImageLayer
}
