// Package integration contains integration tests for the Maven binding that
// exercise the resource repository against a REAL Maven CLI running in a
// container (testcontainers). It validates true interoperability in both
// directions:
//
//   - download: real `mvn deploy:deploy-file` publishes an artifact into a real
//     Maven repository server (Reposilite), and our DownloadResource fetches it
//     back.
//   - upload: our UploadResource publishes an artifact (with sha1/md5) into the
//     same Reposilite server, and real `mvn dependency:get -C` (strict
//     checksums) consumes and validates it.
//
// The repository server is a real Reposilite instance running in its own
// container. The Go code under test reaches it over the mapped host port
// (loopback), while the Maven client container reaches it via testcontainers'
// host-access feature (host.testcontainers.internal).
package integration

import (
	"bytes"
	"context"
	"crypto/md5"
	"crypto/sha1"
	"fmt"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"

	"ocm.software/open-component-model/bindings/go/blob/inmemory"
	credv1 "ocm.software/open-component-model/bindings/go/credentials/spec/config/v1"
	descriptor "ocm.software/open-component-model/bindings/go/descriptor/runtime"
	"ocm.software/open-component-model/bindings/go/maven/repository/resource"
	mavenv1 "ocm.software/open-component-model/bindings/go/maven/spec/access/v1"
	"ocm.software/open-component-model/bindings/go/runtime"
)

// mavenImage is the real Maven CLI used as the interop oracle.
const mavenImage = "maven:3.9.16-eclipse-temurin-11-alpine"

// reposiliteImage is a real Maven repository server used as the repository under test.
// Reposilite has no rolling "3.4" tag published; 3.4.14 is the latest 3.4.x patch.
const reposiliteImage = "dzikoysk/reposilite:3.4.14"

// tokenName and tokenSecret are the credentials for the temporary management
// token generated by Reposilite at startup (see --token). The management token
// has full access to all repository routes (read and write).
const (
	tokenName   = "it"
	tokenSecret = "secret"
	// repoName is the default Reposilite hosted repository used for releases.
	repoName = "releases"
)

// settingsXML disables Maven's default HTTP-repository blocker (empty mirrors)
// so the test can use a plain-HTTP repository and provides credentials for the
// "it" server id used by deploy/get. Passed as both user (-s) and global (-gs)
// settings to fully replace the bundled blocker mirror.
var settingsXML = fmt.Sprintf(`<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
  <servers>
    <server>
      <id>it</id>
      <username>%s</username>
      <password>%s</password>
    </server>
  </servers>
  <mirrors></mirrors>
</settings>
`, tokenName, tokenSecret)

// repoServer is a real Reposilite Maven repository server running in a container.
type repoServer struct {
	c      testcontainers.Container
	port   int
	client *http.Client
}

func newRepoServer(t *testing.T, ctx context.Context) *repoServer {
	t.Helper()
	req := testcontainers.ContainerRequest{
		Image:        reposiliteImage,
		ExposedPorts: []string{"8080/tcp"},
		// Generate a temporary management token so deploy/upload can authenticate.
		Cmd: []string{"--token", tokenName + ":" + tokenSecret},
		WaitingFor: wait.ForHTTP("/api/status/instance").
			WithPort("8080/tcp").
			WithStatusCodeMatcher(func(status int) bool { return status == http.StatusOK }).
			WithStartupTimeout(3 * time.Minute),
	}
	c, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, testcontainers.TerminateContainer(c)) })

	mapped, err := c.MappedPort(ctx, "8080")
	require.NoError(t, err)

	return &repoServer{c: c, port: int(mapped.Num()), client: &http.Client{}}
}

// hostURL is the base repository URL as seen by the Go code under test (host loopback).
func (rs *repoServer) hostURL() string {
	return fmt.Sprintf("http://127.0.0.1:%d/%s", rs.port, repoName)
}

// containerURL is the base repository URL as seen from inside the Maven container.
func (rs *repoServer) containerURL() string {
	return fmt.Sprintf("http://host.testcontainers.internal:%d/%s", rs.port, repoName)
}

// writeFile uploads a file into the repository via an authenticated HTTP PUT.
// Used to seed a .pom (and its checksums) so that `mvn dependency:get` can
// resolve an artifact our code uploaded.
func (rs *repoServer) writeFile(t *testing.T, ctx context.Context, relPath string, data []byte) {
	t.Helper()
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, rs.hostURL()+"/"+relPath, bytes.NewReader(data))
	require.NoError(t, err)
	req.SetBasicAuth(tokenName, tokenSecret)
	resp, err := rs.client.Do(req)
	require.NoError(t, err)
	defer func() { _ = resp.Body.Close() }()
	require.Truef(t, resp.StatusCode >= 200 && resp.StatusCode < 300, "unexpected status %d uploading %q", resp.StatusCode, relPath)
}

// readFile downloads a file from the repository via an authenticated HTTP GET.
func (rs *repoServer) readFile(t *testing.T, ctx context.Context, relPath string) []byte {
	t.Helper()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rs.hostURL()+"/"+relPath, nil)
	require.NoError(t, err)
	req.SetBasicAuth(tokenName, tokenSecret)
	resp, err := rs.client.Do(req)
	require.NoError(t, err)
	defer func() { _ = resp.Body.Close() }()
	require.Equalf(t, http.StatusOK, resp.StatusCode, "unexpected status %d reading %q", resp.StatusCode, relPath)
	data, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	return data
}

// mavenContainer is a long-lived Maven CLI container we exec commands into.
type mavenContainer struct {
	c testcontainers.Container
}

func startMavenContainer(t *testing.T, ctx context.Context, hostPort int) *mavenContainer {
	t.Helper()
	req := testcontainers.ContainerRequest{
		Image: mavenImage,
		// Keep the container alive so we can exec multiple mvn invocations.
		Entrypoint: []string{"sleep"},
		Cmd:        []string{"infinity"},
		// Allow the container to reach the host's repo server.
		HostAccessPorts: []int{hostPort},
		WaitingFor:      wait.ForExec([]string{"sh", "-c", "command -v mvn"}),
	}
	c, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, testcontainers.TerminateContainer(c)) })

	mc := &mavenContainer{c: c}
	// Seed the settings.xml used to bypass the HTTP blocker and provide credentials.
	require.NoError(t, c.CopyToContainer(ctx, []byte(settingsXML), "/work/settings.xml", 0o644))
	return mc
}

// mvn runs an mvn invocation in the container and returns combined output. It
// always passes the permissive settings as both user and global settings.
func (mc *mavenContainer) mvn(t *testing.T, ctx context.Context, args ...string) (int, string) {
	t.Helper()
	full := append([]string{"mvn", "-B", "-s", "/work/settings.xml", "-gs", "/work/settings.xml"}, args...)
	code, reader, err := mc.c.Exec(ctx, full)
	require.NoError(t, err)
	out, _ := io.ReadAll(reader)
	return code, string(out)
}

// deployCredentials returns the credentials used by our resource repository to
// authenticate write operations against Reposilite.
func deployCredentials() runtime.Typed {
	return &credv1.DirectCredentials{
		Type:       runtime.NewVersionedType(credv1.CredentialsType, credv1.Version),
		Properties: map[string]string{"username": tokenName, "password": tokenSecret},
	}
}

func Test_Integration_MavenResourceRepository(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping maven integration test in short mode")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	rs := newRepoServer(t, ctx)
	mc := startMavenContainer(t, ctx, rs.port)
	repo := resource.NewResourceRepository()

	// Direction 1: real Maven deploys -> our DownloadResource reads it back.
	t.Run("download artifact deployed by real maven", func(t *testing.T) {
		const (
			group    = "com.example"
			artifact = "downloaded"
			version  = "1.0.0"
		)
		artifactBytes := []byte("hello-from-real-maven")
		require.NoError(t, mc.c.CopyToContainer(ctx, artifactBytes, "/work/downloaded.jar", 0o644))

		code, out := mc.mvn(t, ctx, "deploy:deploy-file",
			"-Dfile=/work/downloaded.jar",
			"-DgroupId="+group,
			"-DartifactId="+artifact,
			"-Dversion="+version,
			"-Dpackaging=jar",
			"-DrepositoryId=it",
			"-Durl="+rs.containerURL(),
		)
		require.Equalf(t, 0, code, "mvn deploy:deploy-file failed:\n%s", out)

		res := mavenResource(rs.hostURL(), group, artifact, version)
		b, err := repo.DownloadResource(ctx, res, deployCredentials())
		require.NoError(t, err)
		data := readBlob(t, b)
		assert.Equal(t, artifactBytes, data, "downloaded bytes must match what maven deployed")
	})

	// Direction 2: our UploadResource publishes -> real Maven consumes & validates checksums.
	t.Run("upload artifact consumed and checksum-validated by real maven", func(t *testing.T) {
		const (
			group    = "com.example"
			artifact = "uploaded"
			version  = "2.0.0"
		)
		artifactBytes := []byte("uploaded-by-ocm")

		res := mavenResource(rs.hostURL(), group, artifact, version)
		_, err := repo.UploadResource(ctx, res, inmemory.New(bytes.NewReader(artifactBytes)), deployCredentials())
		require.NoError(t, err)

		// Seed a minimal pom (+ checksums) so dependency:get can resolve the GAV.
		// Our UploadResource intentionally uploads only the artifact + checksums.
		base := fmt.Sprintf("%s/%s/%s/%s-%s",
			strings.ReplaceAll(group, ".", "/"), artifact, version, artifact, version)
		pom := []byte(fmt.Sprintf(`<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>%s</groupId>
  <artifactId>%s</artifactId>
  <version>%s</version>
  <packaging>jar</packaging>
</project>
`, group, artifact, version))
		rs.writeFile(t, ctx, base+".pom", pom)
		rs.writeFile(t, ctx, base+".pom.sha1", []byte(fmt.Sprintf("%x", sha1.Sum(pom))))
		rs.writeFile(t, ctx, base+".pom.md5", []byte(fmt.Sprintf("%x", md5.Sum(pom))))

		// Sanity: our upload produced the artifact + checksum siblings.
		gotJar := rs.readFile(t, ctx, base+".jar")
		assert.Equal(t, artifactBytes, gotJar)
		assert.Equal(t, fmt.Sprintf("%x", sha1.Sum(artifactBytes)), string(rs.readFile(t, ctx, base+".jar.sha1")))
		assert.Equal(t, fmt.Sprintf("%x", md5.Sum(artifactBytes)), string(rs.readFile(t, ctx, base+".jar.md5")))

		// -C: strict checksum policy -> fail the build on any checksum mismatch.
		code, out := mc.mvn(t, ctx, "-C", "dependency:get",
			"-DremoteRepositories=it::::"+rs.containerURL(),
			"-Dartifact="+fmt.Sprintf("%s:%s:%s", group, artifact, version),
			"-Dtransitive=false",
		)
		require.Equalf(t, 0, code, "mvn dependency:get (strict checksums) failed:\n%s", out)
	})
}

func mavenResource(repoURL, group, artifact, version string) *descriptor.Resource {
	return &descriptor.Resource{
		Access: &mavenv1.Maven{
			Type:       runtime.NewVersionedType(mavenv1.Type, mavenv1.Version),
			RepoURL:    repoURL,
			GroupID:    group,
			ArtifactID: artifact,
			Version:    version,
		},
	}
}

func readBlob(t *testing.T, b interface {
	ReadCloser() (io.ReadCloser, error)
}) []byte {
	t.Helper()
	rc, err := b.ReadCloser()
	require.NoError(t, err)
	defer rc.Close()
	data, err := io.ReadAll(rc)
	require.NoError(t, err)
	return data
}
