//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/RSAIdentity.schema.json
var schemaRSAIdentity []byte

// JSONSchema returns the JSON Schema for RSAIdentity.
func (RSAIdentity) JSONSchema() []byte {
	return schemaRSAIdentity
}
