//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/TSACredentials.schema.json
var schemaTSACredentials []byte

// JSONSchema returns the JSON Schema for TSACredentials.
func (TSACredentials) JSONSchema() []byte {
	return schemaTSACredentials
}
