//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/DirectCredentials.schema.json
var schemaDirectCredentials []byte

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for DirectCredentials.
func (DirectCredentials) JSONSchema() []byte {
	return schemaDirectCredentials
}
