//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/CopyLocalBlob.schema.json
var schemaCopyLocalBlob []byte

//go:embed schemas/CopyLocalBlobOutput.schema.json
var schemaCopyLocalBlobOutput []byte

//go:embed schemas/CopyLocalBlobSpec.schema.json
var schemaCopyLocalBlobSpec []byte

// JSONSchema returns the JSON Schema for CopyLocalBlob.
func (CopyLocalBlob) JSONSchema() []byte {
	return schemaCopyLocalBlob
}

// JSONSchema returns the JSON Schema for CopyLocalBlobOutput.
func (CopyLocalBlobOutput) JSONSchema() []byte {
	return schemaCopyLocalBlobOutput
}

// JSONSchema returns the JSON Schema for CopyLocalBlobSpec.
func (CopyLocalBlobSpec) JSONSchema() []byte {
	return schemaCopyLocalBlobSpec
}
