//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyLocalBlob) DeepCopyInto(out *CopyLocalBlob) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CopyLocalBlobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CopyLocalBlobOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyLocalBlob.
func (in *CopyLocalBlob) DeepCopy() *CopyLocalBlob {
	if in == nil {
		return nil
	}
	out := new(CopyLocalBlob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CopyLocalBlob) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyLocalBlobOutput) DeepCopyInto(out *CopyLocalBlobOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyLocalBlobOutput.
func (in *CopyLocalBlobOutput) DeepCopy() *CopyLocalBlobOutput {
	if in == nil {
		return nil
	}
	out := new(CopyLocalBlobOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyLocalBlobSpec) DeepCopyInto(out *CopyLocalBlobSpec) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(runtime.Raw)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make(runtime.Identity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyLocalBlobSpec.
func (in *CopyLocalBlobSpec) DeepCopy() *CopyLocalBlobSpec {
	if in == nil {
		return nil
	}
	out := new(CopyLocalBlobSpec)
	in.DeepCopyInto(out)
	return out
}
