//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by typegen. DO NOT EDIT.

package v1

import "ocm.software/open-component-model/bindings/go/runtime"

func (t *OCIImage) SetType(typ runtime.Type) {
	t.Type = typ
}

func (t *OCIImage) GetType() runtime.Type {
	return t.Type
}

func (t *OCIImageLayer) SetType(typ runtime.Type) {
	t.Type = typ
}

func (t *OCIImageLayer) GetType() runtime.Type {
	return t.Type
}
