name: Renovate OCM
on:
    schedule:
        - cron: '0 0 * * 0' # Every Sunday at midnight UTC
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.OCMBOT_APP_ID }}
          private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@13da59cf7cfbd3bfea72ce26752ed22edf747ce9 # v43.0.2
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
        with:
          configurationFile: .github/config/renovate.json5
          token: ${{ steps.generate_token.outputs.token }}