name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '7 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:  # call reusable workflow from central '.github' repo
    permissions:
      issues: write
      pull-requests: write
      contents: read
    uses: open-component-model/.github/.github/workflows/stale.yml@ca1a34b22f6a345cec7741e150cdb43bacedce89 # main