name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '7 1 * * *'
  workflow_dispatch:
    inputs:

permissions:
  contents: read

jobs:
  stale:  # call reusable workflow from central '.github' repo
    permissions:
      issues: write
      pull-requests: write
    uses: open-component-model/.github/.github/workflows/stale.yml@c878408ef4362b719549404c49c47833dba69e5a # main
    secrets: inherit