name: Unit Test

on:
  pull_request:
  push:
    branches:
    - main

env:
  DIR: bindings/go

jobs:
  discover_modules:
    name: "Discover Go Modules"
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.discover.outputs.modules }}
    steps:
    - uses: actions/checkout@v4
    - name: Discover Go Modules
      id: discover
      run: |
        MODULES="$(find ${{ env.DIR }} -name go.mod -exec dirname {} \; | sed 's|${{ env.DIR }}/||' | jq -R -s -c 'split("\n") | map(select(. != ""))')"
        echo "Detected modules: $MODULES"
        echo "modules=$MODULES" >> $GITHUB_OUTPUT

  run_unit_tests:
    name: "Run"
    runs-on: large_runner
    needs: discover_modules
    strategy:
      matrix:
        go-version: [ '1.24.x' ]
        module: ${{ fromJSON(needs.discover_modules.outputs.modules) }}

    steps:
      - name: Self Hosted Runner Post Job Cleanup Action
        uses: TooMuch4U/actions-clean@v2.2

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          sparse-checkout: '${{ env.DIR }}/${{ matrix.module }}'
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ github.workspace }}/${{ env.DIR }}/${{ matrix.module }}/go.mod'
      - name: Run Tests
        run: task bindings/go/${{ matrix.module }}:test
