name: "GitHub Scripts: Verify"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/verify-github-scripts.yml'
      - '.github/scripts/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/verify-github-scripts.yml'
      - '.github/scripts/**'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04-arm
    name: Lint & Test
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            .github/scripts
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .github/scripts/package.json

      - name: Install dependencies
        working-directory: .github/scripts
        run: npm ci

      - name: Lint scripts
        working-directory: .github/scripts
        run: npm run lint

      - name: Run tests
        working-directory: .github/scripts
        run: npm test
