name: "Website: Verify Scripts"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/website-verify-scripts.yml'
      - 'website/assets/js/**'
      - 'website/scripts/**'
      - 'website/eslint.config.*'
      - 'website/package.json'
      - 'website/package-lock.json'
  pull_request:
    branches:
      - main
      - website/**
    paths:
      - '.github/workflows/website-verify-scripts.yml'
      - 'website/assets/js/**'
      - 'website/scripts/**'
      - 'website/eslint.config.*'
      - 'website/package.json'
      - 'website/package-lock.json'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04-arm
    name: Lint & Test
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: website/package.json

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Lint scripts
        working-directory: website
        run: npm run lint:scripts

      - name: Run scripts tests
        working-directory: website
        run: npm test
