name: "Website: Test Install Script"

on:
  pull_request:
    branches:
      - main
      - website/**
    paths:
      - '.github/workflows/website-test-install-script.yml'
      - 'website/static/install-cli.sh'
      - 'website/static/install-cli-test.sh'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test install-cli.sh
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tests
        run: bash website/static/install-cli-test.sh
