//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package artifactory

import (
	_ "embed"
)

//go:embed schemas/Transformation.schema.json
var schemaTransformation []byte

// JSONSchema returns the JSON Schema for Transformation.
func (Transformation) JSONSchema() []byte {
	return schemaTransformation
}
