version: "3"

includes:
  reuse: ../../../../reuse.Taskfile.yml



tasks:
  tmp:
    cmds:
      - mkdir -p tmp
    status:
      - test -d tmp
  test:
    cmds:
      - task: reuse:run-test
    deps:
      - tmp