//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package runtime

import (
	_ "embed"
)

//go:embed schemas/LocalBlob.schema.json
var schemaLocalBlob []byte

// JSONSchema returns the JSON Schema for LocalBlob.
func (LocalBlob) JSONSchema() []byte {
	return schemaLocalBlob
}
